server:
  port:
    8010

spring:
  cloud:
    gateway:
      routes:
        - id: patient-route
          uri: http://localhost:8000/
          predicates:
            - Path=/patient/**
          filters:
            - StripPrefix=1

        - id: note-route
          uri: http://localhost:8001/
          predicates:
            - Path=/note/**
          filters:
            - StripPrefix=1
  main:
    allow-bean-definition-overriding:
      TRUE
